# Generated by Django 4.0.3 on 2022-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_service',
            field=models.IntegerField(default=0),
        ),
    ]
