# Generated by Django 4.0.3 on 2022-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_in_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
